### ISSUE TITLE
新版本的算法我当天已经破解了,会发送到你的邮箱.

### ISSUE THREAD

**Issue by egdw** [Hukeqing/FUCK-NCO-ZJGSU#10]
# 问题描述（请详细的描述你遇到的问题）

6.1时我已经花了几个小时解析了新版的算法,当天已经能够正常使用了.
当然我的项目不便开源,我可以将相关算法发送到你的邮箱,请查收.

# 设备（请详细的描述你使用的方式，若是个人设备，请描述设备的操作系统、版本、环境）

😋

**Comment by egdw** [comment]
新的算法用了如下的工具对代码进行了混淆:
[js混淆工具](https://obfuscator.io/)

**Comment by Hukeqing** [comment]
非常感谢
