### ISSUE TITLE
[Bug]: pip install -r requirements.txt

### ISSUE THREAD

**Issue by jujimeizuo** [Hukeqing/FUCK-NCO-ZJGSU#11]
因为*.sh里用的是python3，所以install应该用pip3

**Comment by Hukeqing** [comment]
pip 是 python 的包管理系统的意思，pip3 也是 pip，如果电脑中只有 python3，则只有 pip 而不一定有 pip3，当看到 pip 时候，应该根据自己的环境明确自己应该使用哪个 pip。准确来说，我们指的 pip 并不是你所谓的常见的那个 pip，而是 `python -m pip`
