### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Hukeqing** [Hukeqing/FUCK-NCO-ZJGSU#5]
@uselessbug 
能否调整一下文件的名称等文件目录结构之类的内容，目前的 index 和 main 两个文件拥有过多相似的代码，是否可以合并

**Comment by uselessbug** [comment]
抱歉！！！现在才看到（...）
我尽量抽空合并，不过云战役似乎要换新版了？）

**Comment by Hukeqing** [comment]
先看情况吧，估摸着可能是要下个学期开始了吧，我应该之后就不管了

**Comment by Hukeqing** [comment]
> 抱歉！！！现在才看到（...）
> 我尽量抽空合并，不过云战役似乎要换新版了？）

我看了一下学校的新的云战役，应该还是老套路，直接抓包获取请求就行，定位地址应该还是在用高德的 API 然后进行本地定位而不是真实定位的，估计是那个恒生电子外包公司也就只会这种办法。

不过就目前这个学校的框架来看，也只能这样搞。毕竟恒生只会搞 uniapp，那就被限制死在浏览器安全策略上了

**Comment by uselessbug** [comment]
> > 抱歉！！！现在才看到（...）
> > 我尽量抽空合并，不过云战役似乎要换新版了？）
> 
> 我看了一下学校的新的云战役，应该还是老套路，直接抓包获取请求就行，定位地址应该还是在用高德的 API 然后进行本地定位而不是真实定位的，估计是那个恒生电子外包公司也就只会这种办法。
> 
> 不过就目前这个学校的框架来看，也只能这样搞。毕竟恒生只会搞 uniapp，那就被限制死在浏览器安全策略上了

> 

是的，可以直接post。但是获取token比老版麻烦好多（....

**Comment by Hukeqing** [comment]
@uselessbug 新版本云战役已经破解，从通知我要用新版到现在一共花费了两个小时，并且我还顺便吃了个夜宵
