### ISSUE TITLE
[BUG]按步骤操作下来但是没有打卡成功请问是什么原因呢

### ISSUE THREAD

**Issue by zzzzzxp1** [Hukeqing/FUCK-NCO-ZJGSU#6]
# 问题描述（请详细的描述你遇到的问题）
云战役打卡步骤都完成了 但是观察了两天好像都没有给我自动打卡 请问还需要别的什么步骤吗
# 设备（请详细的描述你使用的方式，若是个人设备，请描述设备的操作系统、版本、环境）

**Comment by Hukeqing** [comment]
能否提供一些信息
 - 你想要使用哪个打卡程序，“云战役”还是“我的商大”，或是两者
 - 你采用了什么方案，例如云战役有三种方案：a. 服务器，b. GitHub Action，c. 腾讯云，而后者仅一个方案

**Comment by zzzzzxp1** [comment]
> * 个打卡程序，“云战役”还是“我的商大”，或是两



> 能否提供一些信息
> 
> * 你想要使用哪个打卡程序，“云战役”还是“我的商大”，或是两者
> * 你采用了什么方案，例如云战役有三种方案：a. 服务器，b. GitHub Action，c. 腾讯云，而后者仅一个方案

**Comment by zzzzzxp1** [comment]
> 能否提供一些信息
> 
> * 你想要使用哪个打卡程序，“云战役”还是“我的商大”，或是两者
> * 你采用了什么方案，例如云战役有三种方案：a. 服务器，b. GitHub Action，c. 腾讯云，而后者仅一个方案

我使用的是“云战役”，采用方案a服务器（直接拉取源码部署）。
在实验室的电脑（linux系统）上按步骤进行操作了。我看也添加成功了定时任务，不知道问题出在哪里，服务器的问题嘛？

**Comment by Hukeqing** [comment]
> > 能否提供一些信息
> > 
> > * 你想要使用哪个打卡程序，“云战役”还是“我的商大”，或是两者
> > * 你采用了什么方案，例如云战役有三种方案：a. 服务器，b. GitHub Action，c. 腾讯云，而后者仅一个方案
> 
> 我使用的是“云战役”，采用方案a服务器（直接拉取源码部署）。 在实验室的电脑（linux系统）上按步骤进行操作了。我看也添加成功了定时任务，不知道问题出在哪里，服务器的问题嘛？

可以尝试一下主动执行代码的结果吗

如果你是按照我提供的目录，则应该是这样的命令，如果目录有调整，请自行更新一下命令

```shell
cd /root/FUCK-NCO-ZJGSU
./start.sh
```

执行后看看有没有什么反馈信息，如果有任何的反馈信息，那么将其发送给我，如果没有的话再将执行下面的命令看看输出情况，将输出给我

```shell
cd /root/FUCK-NCO-ZJGSU
cat ./out.txt
```

**Comment by Hukeqing** [comment]
可以不关心时间点，不论是不是已经打过卡了

**Comment by zzzzzxp1** [comment]
> > > 能否提供一些信息
> > > 
> > > * 你想要使用哪个打卡程序，“云战役”还是“我的商大”，或是两者
> > > * 你采用了什么方案，例如云战役有三种方案：a. 服务器，b. GitHub Action，c. 腾讯云，而后者仅一个方案
> > 
> > 
> > 我使用的是“云战役”，采用方案a服务器（直接拉取源码部署）。 在实验室的电脑（linux系统）上按步骤进行操作了。我看也添加成功了定时任务，不知道问题出在哪里，服务器的问题嘛？
> 
> 可以尝试一下主动执行代码的结果吗
> 
> 如果你是按照我提供的目录，则应该是这样的命令，如果目录有调整，请自行更新一下命令
> 
> ```shell
> cd /root/FUCK-NCO-ZJGSU
> ./start.sh
> ```
> 
> 执行后看看有没有什么反馈信息，如果有任何的反馈信息，那么将其发送给我，如果没有的话再将执行下面的命令看看输出情况，将输出给我
> 
> ```shell
> cd /root/FUCK-NCO-ZJGSU
> cat ./out.txt
> ```

27日使用./start.sh发现里面路径跟我不一致，更改后执行无任何反馈信息。然后执行./out.txt反馈如下:
2021-12-27 报送情况： *主动报送*
28日我观察仍然没有自动打卡，执行./out.txt反馈如下:
2021-12-27 报送情况： *主动报送*
2021-12-27 报送情况： *主动报送*
2021-12-28 报送情况： *主动报送*

**Comment by Hukeqing** [comment]
按照描述，应该是没有问题的

大概率是你设置的打卡时间晚于你查看的时间了，或者你写入文件的账号密码是别人的账号密码了

需要确认几个事情
 - 你设置的打卡时间是什么时候，即在第三步，`crontab -e` 后，添加的时间是什么，如果你不确定或者不理解，你可以将原内容发一下。以及你的查看时间是什么时候，推荐采用提供的时间，即 `5 0 * * * /root/FUCK-NCO-ZJGSU/start.sh` 这样的，注意路径需要更换！！！
 - 检查一下你的账号密码是否与你手机上查看的用户账号密码是否对应，账号密码位于 `user.json` 文件内

**Comment by zzzzzxp1** [comment]
> 

采用的是5 0 * * * /root/FUCK-NCO-ZJGSU/start.sh。经过提醒发现这里的路径忘记改了，已更正。
更正后执行./start.sh以及./out.txt后反馈如下：
2021-12-28 报送情况： 报送失败！！！！！

已检查过账号密码是对应的。

**Comment by zzzzzxp1** [comment]
> 

采用的是5 0 * * * /root/FUCK-NCO-ZJGSU/start.sh。经过提醒发现这里的路径忘记改了，已更正。
更正后执行./start.sh以及./out.txt后反馈如下：
2021-12-28 报送情况： 报送失败！！！！！

已检查过账号密码是对应的。

**Comment by Hukeqing** [comment]
之前显示报送是成功的啊，即能够登陆成功啊，为什么更新之后反而会失败……
你除了更新这个路径之外，还更新过地方吗

**Comment by Hukeqing** [comment]
我去检查了一下，发现云战役是必须早上报送的，下午报送必定会失败，现在应该已经OK了，明天会正常报送了，你明天再看看如何吧

**Comment by zzzzzxp1** [comment]
> 

好滴好滴，感谢细心的回复~

**Comment by Hukeqing** [comment]
> 好滴好滴，感谢细心的回复~

如果成功了的话，我就把 issue 关掉了

**Comment by zzzzzxp1** [comment]
> > 好滴好滴，感谢细心的回复~
> 
> 如果成功了的话，我就把 issue 关掉了

成功啦成功啦，谢谢指导~~
