### ISSUE TITLE
跟着更新了云函数版本

### ISSUE THREAD

**Issue by yujianke100** [Hukeqing/FUCK-NCO-ZJGSU#7]
云函数版，家境贫寒者首选：
https://github.com/yujianke100/AUTO-FUCK-NCO-ZJGSU

本体部分修改只是精简了下输出，加了个失败发邮件。

**Comment by Hukeqing** [comment]
请在项目的README文件开头的明显位置，注明本项目地址

**Comment by yujianke100** [comment]
> 

标注了。原来仓库不是fork来的，这边也删了重新fork了

**Comment by Hukeqing** [comment]
晚上我搞一下，现在在上班
