### ISSUE TITLE
[BUG]签到失效

### ISSUE THREAD

**Issue by yujianke100** [Hukeqing/FUCK-NCO-ZJGSU#8]
# 问题描述（请详细的描述你遇到的问题）
token似乎正常获取，但最后的post出现问题。估计是学校更新后台了。

**Comment by Hukeqing** [comment]
目前搞了一个小时，确定了一下问题
多了两个参数，而且后端进行校验了，其中一个跟时间有关，已经破解，目前不确定有没有过期限制，另外一个似乎是一个散列函数的结果，但是其中还有一个未知量我没有找出来，是一个和身份有关的量
先去上班，晚上再说

**Comment by Hukeqing** [comment]
已经更新，淦它！
